### ISSUE TITLE
TypeError raised when formatting or validating incorrect heredoc definitions

### ISSUE THREAD

**Issue by rcjsuen** [rcjsuen/dockerfile-utils#127]
Both of these files will fail with the same error.
```JavaScript
const lib = require("dockerfile-utils");
lib.validate("RUN <<<test\ntest\n")
```
```JavaScript
const lib = require("dockerfile-utils");
lib.validate("RUN <<'test\ntest\n")
```
```
$ node test.js
./node_modules/dockerfile-ast/lib/instruction.js:842
            const startRange = arg.getRange();
                                   ^

TypeError: Cannot read properties of undefined (reading 'getRange')
    at Run.getHeredocs (./node_modules/dockerfile-ast/lib/instruction.js:842:36)
    at Run.getHeredocs (./node_modules/dockerfile-ast/lib/instructions/run.js:19:22)
    at Validator.getHeredocLines (./node_modules/dockerfile-utils/lib/dockerValidator.js:309:47)
    at Validator.validateInstruction (./node_modules/dockerfile-utils/lib/dockerValidator.js:348:43)
    at Validator.validate (./node_modules/dockerfile-utils/lib/dockerValidator.js:272:18)
    at Object.validate (./node_modules/dockerfile-utils/lib/main.js:165:22)
    at Object.<anonymous> (./test.js:2:5)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)

Node.js v20.16.0
```

**Comment by rcjsuen** [comment]
The error will also be raised when trying to format the file.
```JavaScript
const lib = require("dockerfile-utils");
lib.format("RUN <<<test\ntest\n")
```
```
/dockerfile-language-server/node_modules/dockerfile-ast/lib/instruction.js:842
            const startRange = arg.getRange();
                                   ^

TypeError: Cannot read properties of undefined (reading 'getRange')
    at Run.getHeredocs (/dockerfile-language-server/node_modules/dockerfile-ast/lib/instruction.js:842:36)
    at Run.getHeredocs (/dockerfile-language-server/node_modules/dockerfile-ast/lib/instructions/run.js:19:22)
    at DockerFormatter.format (/dockerfile-language-server/node_modules/dockerfile-utils/lib/dockerFormatter.js:178:46)
    at DockerFormatter.formatDocument (/dockerfile-language-server/node_modules/dockerfile-utils/lib/dockerFormatter.js:98:21)
    at Object.format (/dockerfile-language-server/node_modules/dockerfile-utils/lib/main.js:144:22)
    at Object.<anonymous> (/dockerfile-language-server/test.js:2:5)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)

Node.js v20.16.0
```
